### ISSUE TITLE
Separate `warp-grpc` core from each library

### ISSUE THREAD

**Issue by serras** [lucasdicioccio/warp-grpc#3]
This is a follow-up to #2, in which support for `proto3-wire` is added to the library. Since there is more that one library for Protocol Buffers serialization, it makes sense to provide the user the ability to choose it.

My proposal is to split the library into three libraries:

1. `warp-grpc-core`, which contains `Network.GRPC.Server.Wai`, `Network.GRPC.Server.Helpers`, and `Network.GRPC.Server` (but without the exposed functions from `Handlers`). This package would not depend on `proto-lens` nor `proto3-wire`.
2. `warp-grpc-proto-lens`, which contains the current `Network.GRPC.Server.Handlers` module renamed to `Network.GRPC.Server.Handlers.ProtoLens`.
3. `wrap-grpc-proto3-wire`, which contains the current `Network.GRPC.Server.Handlers.NoLens` renamed to `Network.GRPC.Server.Handlers.ProtoWire`.

I volunteer to do all of this work. Furthermore, with the multi-package support from Stack, we can just keep one single repo for all the libraries.

**Comment by lucasdicioccio** [comment]
I think it also makes sense because gRPC (as a technology) also allows to change serializations. So we'll need to be able to be somewhat parametric on serialization anyway at some point.

Regarding repositories: +1 for a single repo and multiple packages. Do you think we should regroup more grpc-related packages in it? (I could keep http2-client out and all the grpc-related into some "grpc-native" big repo for people who want a native and compatible alternative to the official C-based libraries).

**Comment by serras** [comment]
That could be a great idea, indeed. However, note that `proto-lens` is very intertwined right now with the packages. One would need to split:

* `http2-grpc-types`, because the `Encoding` module uses `proto-lens` types.
* `warp-grpc`,
* `http2-client-grpc`, in fact for this I have already implemented support for `proto3-wire` in https://github.com/47deg/http2-client-grpc.

**Comment by serras** [comment]
But I have also an idea for a design which would minimize the amount of packages. The main difference between using `proto-lens` and `proto3-wire` are (1) serialization, and (2) representation of RPC methods. I propose to split in only 5 packages:

* `http2-grpc-types`, without the `Encoding` module, but with data types and type clases to support (1) and (2).
* `http2-grpc-types-proto-lens` and `http2-grpc-types-proto3-wire`, which provide the instances for the two libraries we want to support.
* `warp-grpc` and `http2-client-grpc` would just depend in `http2-grpc-types`, and then you choose which serialization library you want to use by picking one of the other packages.

If you agree on this plan, I volunteer to do all this work. Maybe we can create a new repo `http2-grpc` to host all of this as a multi-package repo.

By the way, I forgot to thank you for all this hard work. I was looking for a gRPC library for Haskell, and yours was both easy to use and easy to tinker with :)

**Comment by lucasdicioccio** [comment]
Hi again! This looks like a good plan. We have to see how it panes out but I think that having multiple "implementations" will even make the codebase stronger.

As you can see I'm somewhat busy these days: I'll have some spare days in November (we have some bank holidays). So go ahead without me. Starting end of this week I'll start helping on the organizational bits and if I find "code time" I'll try to think what we need on medium term I had not time to setup so far (more examples and tutorials, automated compatibility tests, generated-stubs for some famous services etc.)

Thank you for your supportive messages. I'm happy you found my code easy to tinker with, and "easy to use" was part of the plan! Let's re-use such examples to show Haskell is actually good at maintenance in enterprise-technologies-setups.

**Comment by serras** [comment]
As promised, here is the multi-repo in which the `proto-lens` and `proto3-wire` support is separated from the `warp-grpc` and `http2-client-grpc` packages -> https://github.com/higherkindness/http2-grpc-haskell

**Comment by lucasdicioccio** [comment]
Hi @serras this is excellent. I'll have a look this week-end, setup an organization, and do some announcement on Reddit in case we find more partygoers!

**Comment by serras** [comment]
Maybe we do not need an organization for this, since the entire project is now one single repo ;)

**Comment by lucasdicioccio** [comment]
I think having an organization would clarify things for external users and probably make managing ACLs a simpler thing if we can (hopefully) bring in even more developers.

For things that are "around" but I would like to organize under a same umbrella are:
- examples
- stubs for some common .proto services (e.g., etcd)

What do you think?

**Comment by serras** [comment]
I am a lover of mono-repos, so my first instinct is to put everything under the same repo. That way examples and stubs can never become out-of-date, because they are built along the main libraries.

But of course, you are the one to decide. I am happy to help in whatever organizational form you choose.

**Comment by serras** [comment]
Anyway, it would be great if we could make a release of the new set of packages and let the world know about them!

**Comment by lucasdicioccio** [comment]
Just created https://github.com/haskell-grpc-native and made yourself an owner.

We need to:
- [x] start pointing toward this org/repo
- [x] migrate monorepo to the org
- [x] sort of migrate the issues
- [x] update the monorepo's README with proper links (https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/7)
- [x] publish packages
- [ ] make an announcement on reddit/the caffe
- [ ] import other packages like examples, etcd, benchmarks

I'm working the list top down starting now.

**Comment by lucasdicioccio** [comment]
Oh saint-UX-rats! @serras : I can't open issues on the fork at the org.
Do you know if there is some button in GitHub to do so? Else we can just close and re-push the repo (or we can make an Issue-only repo).

**Comment by serras** [comment]
I might need to transfer the repo to the new organization. I'll do it in
the following hours.

**Comment by serras** [comment]
Fixed! It seems that by default forks do not have issues enabled. They are not enabled.

**Comment by serras** [comment]
As you can see, I have taken the liberty to "port" some of the pull requests to the new repo and set up Travis for continuous integration.

**Comment by lucasdicioccio** [comment]
OK, I'm done "porting" (at least referencing) all the issues except for one: the `etcd` package will wait. Like the goofy person I am, I found the "transfer issue" button a bit late.

**Comment by lucasdicioccio** [comment]
https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/7 fixes all the links and add some README context

**Comment by lucasdicioccio** [comment]
@serras I've published all packages \o/

**Comment by lucasdicioccio** [comment]
I think we can continue on the other repo!

**Comment by serras** [comment]
Great news! Should I include them in Stackage too?

**Comment by lucasdicioccio** [comment]
I’d also need to make effort to push http2-client onto stackage.
So far I was a bit low on OSS-energy (but your contributions pumped-me up :-) ).
Let’s have stackage as a goal for X-mas?
—
Lucas

**Comment by serras** [comment]
If all the packages are in Hackage, I can send the request for inclusion in
Stackage tomorrow ;)
